name: notes_app
description: A Note-Taking App with Offline Sync

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # Functional Programming
  dartz: ^0.10.1

  # UI
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0

  # Utils
  uuid: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true